version: '3.8'

services:
  youtube-video-download-worker-0:
    image: "poikkjfg200/pku-ece-cv:03-11"
    deploy:
      replicas: 12
    environment:
      - CLOUD_CONFIG=external
      - GFW=false
    restart: always
    command:
      [
          "bash",
          "-c",
    "conda run --no-capture-output --name pku-ece-cv rq worker GCC_spider --url redis://:cGt1X3JlZGlz@43.128.114.151:6379 --path ./ --name  GCC-spider-worker-$$RANDOM"
      ]
