version: '3.8'

services:
  youtube-video-download-worker-0:
    image: "poikkjfg200/pku-ece-cv:update-1b-77"
    deploy:
      replicas: 8
    environment:
      - CLOUD_CONFIG=external
      - GFW=false
    restart: always
    command:
      [
          "bash",
          "-c",
    "conda run --no-capture-output --name pku-ece-cv rq worker 1b_spider_1 --url redis://:cGt1X3JlZGlz@43.154.52.77:6379 --path ./ --name  1bb-spider-worker-$$RANDOM"
      ]