version: '3.8'

services:
  youtube-video-download-worker-0:
    image: "panda1024/pku-ece-cv:v2.3"
    deploy:
      replicas: 12
    environment:
      - CLOUD_CONFIG=external
      - GFW=false
    restart: always
    command:
      [
          "bash",
          "-c",
          "conda run --no-capture-output --name pku-ece-cv rq worker GCC_spider --url redis://43.156.121.84:cGt1X3JlZGlz@:6379 --path ./ --name  GCC-spider-worker-$$RANDOM"
      ]
